cmake_minimum_required(VERSION 3.5)

project(PixeonImageViewer VERSION 1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Widgets Core Gui)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets Core Gui)

add_executable(PixeonImageViewer
    main.cpp
    main.h
    MainWindow.cpp
    MainWindow.h
    ImageViewer.cpp
    ImageViewer.h
    ImageProcessor.cpp
    ImageProcessor.h
    CanvasImageItem.cpp
    CanvasImageItem.h
)

target_link_libraries(PixeonImageViewer PRIVATE Qt${QT_VERSION_MAJOR}::Widgets Qt${QT_VERSION_MAJOR}::Core Qt${QT_VERSION_MAJOR}::Gui)


